name: Nightly Docker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  server_docker:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.2.6
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          # To access redis service https://github.com/docker/build-push-action/discussions/1020#discussioncomment-7763919
          driver-opts: network=host
      - uses: docker/build-push-action@v6
        with:
          context: server
          tags: server:latest
          push: false

  server_development_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: server
          file: server/Dockerfile.development
          tags: server_development:latest
          push: false

  client_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: client
          tags: client:latest
          push: false

  client_development_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: client
          file: client/Dockerfile.development
          tags: client_development:latest
          push: false
